# Generated by Django 5.0.4 on 2024-04-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.FloatField(default=10000.0),
        ),
    ]
