# Generated by Django 5.0.4 on 2024-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='watchlist',
            field=models.JSONField(default=list),
        ),
    ]
