# Generated by Django 5.0.4 on 2024-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_users_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cache',
            field=models.JSONField(default=list),
        ),
    ]
