# Generated by Django 5.1.4 on 2025-10-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_users_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cache',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='stockbuy',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='stocksold',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='watchlist',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocknames', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(max_length=7)),
                ('price', models.FloatField(max_length=25.0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
