# Generated by Django 5.1.4 on 2025-10-28 15:58

import app1.mdate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_users_cache_alter_users_stockbuy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='time',
            field=models.DateField(default=app1.mdate.todaydate),
        ),
    ]
